import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import LotteryEntrance from "../components/LotteryEntrance";
import { useMoralis } from "react-moralis";
import { Illustration } from 'web3uikit';
import { clearPreviewData } from "next/dist/server/api-utils";


const supportedChains = ["31337", "4"];

export default function Home() {
  const { isWeb3Enabled, chainId } = useMoralis();

  return (
    <div className={styles.container}>
      <Head>
        <title>Resistanc3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      
      

      <div className={styles.title}>
          <h1>We are a DAO Community</h1>

          {isWeb3Enabled ? (
        <div>
          {supportedChains.includes(parseInt(chainId).toString()) ? (
            <div className="flex flex-row">
              <LotteryEntrance className="p-8" />
            </div>
          ) : (
            <div style={{color: "red"}}>{`Please switch to a supported chainId. The supported Chain Ids are: ${supportedChains}`}</div>
          )}
        </div>
      ) : (
        <div style={{color: "red"}}>Please connect to a Wallet</div>
      )}


          <div className={styles.pointer}></div>
          <img src="https://github.com/itsjenm/resistanc3/blob/main/img/resistanc3_High_Res_Logo.png?raw=true" className="logo" style={{ width: "40%", height: "auto"}}></img>
          

          <div className={styles.pointer2}>
          </div>


      </div>
      <h1 style={{textAlign: "center", color: "green"}}>How it works\\</h1>
      <div className={styles.main}>
    

      <div className={styles.grid}>
      <Illustration logo="pack" />
      </div>

      <div className={styles.description}>
        <h3 style={{color: "blue" }}>Learn Cybersecurity\\</h3>
        <p style={{fontSize: "18px"}}>Work through the series of challenges that will help you gain analytical skills in Cybersecurity.</p>
      </div>
      </div>
      <div className={styles.grid2}>
        <p>
        <h3 style={{textAlign: "center", color: "blue"}}>Hack-To-Earn</h3>
        <ul>
          <li>1. Pick your level of experience</li>
          <li>2. Decrypt NFT</li>
          <li>3. Earn an NFT badge, tokems, and more</li>
          </ul></p>
      </div>
    </div>
  );

}
